__author__ = 'Juanjose Gutierrez'
__email__ = 'djj_86@hotmail.com'
__license__ = 'MIT'
__summary__ = 'Cython template for creating command line applications.'
__url__ = 'https://github.com'
__version__ = '0.1.0'
